fix(action.yml): Correct typo in qemu-loongarch64 commands

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -102,8 +102,8 @@ runs:
         *)
             cpu=${{ inputs.cpu }}
         esac
-        sudo update-binfmts --unimport qemu-lonngarch64 || echo "warning: could not unimport qemu-arm"
-        sudo update-binfmts --package lonngarch-runner-action --install lonngarch-runner-action-qemu-lonngarch64 /usr/bin/qemu-lonngarch64 --magic '\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x02\x01' --mask '\xff\xff\xff\xff\xff\xff\xff\xfc\x00\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff' --credentials yes --fix-binary yes
+        sudo update-binfmts --unimport qemu-loongarch64 || echo "warning: could not unimport qemu-loongarch64"
+        sudo update-binfmts --package loongarch-runner-action --install loongarch-runner-action-qemu-loongarch64 /usr/bin/qemu-loongarch64 --magic '\x7f\x45\x4c\x46\x02\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x02\x00\x02\x01' --mask '\xff\xff\xff\xff\xff\xff\xff\xfc\x00\xff\xff\xff\xff\xff\xff\xff\xfe\xff\xff\xff' --credentials yes --fix-binary yes
     - name: Download base image
       run: |
         sudo --preserve-env=GITHUB_OUTPUT bash ${GITHUB_ACTION_PATH}/download_image.sh ${{ inputs.base_image }}
